services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - symfony-php
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./backend:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  symfony-php:
    image: php:8.2-fpm
    volumes:
      - ./backend:/var/www/html