version: '3.8'

services:
  traefik:
    image: traefik:3.2.3
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"

  spa:
    image: nginx:latest
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spa.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.spa.priority=1"
      - "traefik.http.services.spa.loadbalancer.server.port=80"

  symfony-php:
    image: php:8.2-fpm
    volumes:
      - ./backend:/var/www/html

  symfony-nginx:
    image: nginx:latest
    depends_on:
      - symfony-php
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.priority=10"
      - "traefik.http.services.api.loadbalancer.server.port=80"