services:
  traefik:
    image: traefik:3.2.3
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"

  nginx:
    image: nginx:latest
    depends_on:
      - symfony-php
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./backend:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.web.priority=1"
      - "traefik.http.services.web.loadbalancer.server.port=80"

  symfony-php:
    image: php:8.2-fpm
    volumes:
      - ./backend:/var/www/html